
"use client";

import { useState, useEffect } from 'react';
import { Check, Copy, Share2, Twitter, Linkedin, MessageCircle, Instagram } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { InlineMessage } from '@/components/ui/inline-message';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";

interface CaptionCardProps {
  caption: string;
  index: number;
}

export function CaptionCard({ caption, index }: CaptionCardProps) {
  const [copied, setCopied] = useState(false);
  const [inlineMessage, setInlineMessage] = useState<string | null>(null);
  const [canNativeShare, setCanNativeShare] = useState(false);

  useEffect(() => {
    if (typeof navigator !== 'undefined' && 'share' in navigator) {
      setCanNativeShare(true);
    }
  }, []);

  const handleCopy = (e?: React.MouseEvent) => {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }

    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(caption)
        .then(() => {
          setCopied(true);
          setInlineMessage("Copied to clipboard! ✨");
        })
        .catch((err) => {
          console.error('❌ Failed to copy to clipboard:', err);
          fallbackCopyTextToClipboard(caption);
        });
    } else {
      fallbackCopyTextToClipboard(caption);
    }

    setTimeout(() => {
      setInlineMessage(null);
    }, 2000);
  };

  const fallbackCopyTextToClipboard = (text: string) => {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    try {
      const successful = document.execCommand('copy');
      if (successful) {
        setCopied(true);
        setInlineMessage("Copied to clipboard! ✨");
      } else {
        setInlineMessage("Copy failed. Please select and copy manually.");
      }
    } catch (err) {
      console.error('❌ Fallback copy failed:', err);
      setInlineMessage("Copy failed. Please select and copy manually.");
    }

    document.body.removeChild(textArea);
  };

  const marketingSuffix = "\n\n✨ Generated by Capsera - Create viral captions in seconds!\n👉 Try it free: https://capsera.vercel.app";

  const handleNativeShare = async () => {
    const shareText = `${caption}${marketingSuffix}`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Check out this caption!',
          text: shareText,
        });
      } catch (err) {
        console.error('Error sharing:', err);
      }
    }
  };

  const openSocialLink = (platform: string) => {
    let url = '';
    const shareText = `${caption}${marketingSuffix}`;
    const encodedText = encodeURIComponent(shareText);

    switch (platform) {
      case 'twitter':
        url = `https://twitter.com/intent/tweet?text=${encodedText}`;
        break;
      case 'linkedin':
        // LinkedIn text sharing is limited, usually requires a URL. 
        // We'll try the feed share, but often just copying is better.
        // Using a workaround or just copying.
        handleCopy();
        window.open(`https://www.linkedin.com/feed/?shareActive=true`, '_blank');
        return;
      case 'whatsapp':
        url = `https://wa.me/?text=${encodedText}`;
        break;
      case 'instagram':
        // Instagram doesn't support direct web sharing. Copying is the best action.
        // We copy the text WITH the marketing suffix.
        if (navigator.clipboard && navigator.clipboard.writeText) {
          navigator.clipboard.writeText(shareText)
            .then(() => {
              setInlineMessage("Copied with link! Open Instagram.");
            })
            .catch(() => fallbackCopyTextToClipboard(shareText));
        } else {
          fallbackCopyTextToClipboard(shareText);
          setInlineMessage("Copied with link! Open Instagram.");
        }
        setTimeout(() => setInlineMessage(null), 3000);
        return;
    }

    if (url) {
      window.open(url, '_blank');
    }
  };

  useEffect(() => {
    if (copied) {
      const timer = setTimeout(() => {
        setCopied(false);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [copied]);

  return (
    <div className="group bg-[#F2EFE5]/20 dark:bg-muted/20 transition-colors duration-300 flex flex-col justify-between min-h-[180px] border border-[#C7C8CC]/80 dark:border-border hover:border-[#B4B4B8]/90 dark:hover:border-border/70 rounded-xl shadow-sm hover:shadow-md overflow-hidden">
      {/* Caption Content - Full Display */}
      <div className="p-4 flex-grow overflow-auto max-h-[300px]">
        <p className="text-foreground/90 text-sm leading-relaxed whitespace-pre-wrap break-words">{caption}</p>
      </div>

      {/* Action Buttons - Compact */}
      <div className="p-3 border-t border-[#C7C8CC]/50 dark:border-border/50 bg-[#E3E1D9]/10 dark:bg-muted/10 flex gap-2">
        {/* Copy Button - Primary Action */}
        <Button
          type="button"
          onClick={handleCopy}
          variant="ghost"
          size="sm"
          className="flex-1 h-9 text-sm text-muted-foreground hover:bg-primary/10 hover:text-primary transition-colors rounded-lg"
        >
          {copied ? (
            <>
              <Check className="mr-2 h-4 w-4 text-green-500" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="mr-2 h-4 w-4" />
              Copy
            </>
          )}
        </Button>

        {/* Share Menu */}
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              className="h-9 w-9 px-0 text-muted-foreground hover:bg-primary/10 hover:text-primary transition-colors rounded-lg"
            >
              <Share2 className="h-4 w-4" />
              <span className="sr-only">Share</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-48">
            {canNativeShare && (
              <>
                <DropdownMenuItem onClick={handleNativeShare}>
                  <Share2 className="mr-2 h-4 w-4" />
                  <span>Share via...</span>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
              </>
            )}
            <DropdownMenuItem onClick={() => openSocialLink('twitter')}>
              <Twitter className="mr-2 h-4 w-4" />
              <span>Twitter / X</span>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => openSocialLink('whatsapp')}>
              <MessageCircle className="mr-2 h-4 w-4" />
              <span>WhatsApp</span>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => openSocialLink('linkedin')}>
              <Linkedin className="mr-2 h-4 w-4" />
              <span>LinkedIn</span>
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => openSocialLink('instagram')}>
              <Instagram className="mr-2 h-4 w-4" />
              <span>Instagram (Copy)</span>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </div>
  );
}
